Repository gwpy/gwsumm, pull requests merged in 2019-03, with the labels that each got.

#223 Avoid build test failures
  gwsumm/data/utils.py
  gwsumm/plot/__init__.py
  gwsumm/tests/test_data.py
  requirements.txt
  setup.py
Labels: bug-fix, build-and-test, enhancement, gwpy, plotter

#226 Use pygments to render config files
  gwsumm/html/bootstrap.py
  gwsumm/html/utils.py
  requirements.txt
  setup.py
Labels: backwards-compatible, config, enhancement, html, python3

#227 Bugfix for segment histograms
  gwsumm/plot/range.py
  gwsumm/plot/segments.py
Labels: backwards-compatible, bug-fix, gwpy

#228 Resolve a bug in ISC noise budget plots
  gwsumm/data/mathutils.py
  gwsumm/plot/noisebudget.py
Labels: backwards-compatible, bug-fix

#224 Handle gaps in Virgo h(t) channels
  gwsumm/data/timeseries.py
Labels: backwards-compatible, bug-fix, enhancement, gwpy

#230 Proper fix for histogram axes when sep=True
  gwsumm/plot/segments.py
Labels: enhancement, plotter
