Repository gwpy/gwsumm, pull requests merged in 2019-04, with the labels that each got.

#241 Use gwdetchar.io.html to write footers
  gwsumm/html/bootstrap.py
  gwsumm/html/utils.py
  gwsumm/tabs/core.py
  requirements.txt
  setup.py
Labels: html

#242 Export HTML tables to CSV using javascript
  gwsumm/html/tables.py
  gwsumm/tabs/data.py
  gwsumm/tabs/etg.py
  gwsumm/tabs/gracedb.py
  gwsumm/tabs/guardian.py
  gwsumm/tabs/management.py
  gwsumm/tabs/sei.py
  share/js/gwsumm.js
  share/sass/gwsumm.scss
Labels: enhancement, html, triggers

#244 Write HDF5 summary after every tab
  bin/gw_summary
Labels: enhancement

#245 Support combined time-volume estimates
  gwsumm/plot/range.py
Labels: enhancement, feature-request

#246 Added protections against network range issues
  gwsumm/plot/range.py
Labels: bug-fix, enhancement

#248 Use backports configparser package for python < 3.6
  bin/gw_summary
  bin/gwsumm-plot-guardian
  gwsumm/config.py
  gwsumm/data/timeseries.py
  gwsumm/plot/segments.py
  gwsumm/plot/sei.py
  gwsumm/segments.py
  gwsumm/state/core.py
  gwsumm/tabs/builtin.py
  gwsumm/tabs/core.py
  gwsumm/tabs/data.py
  gwsumm/tabs/etg.py
  gwsumm/tabs/gracedb.py
  gwsumm/tabs/guardian.py
  gwsumm/tabs/management.py
  gwsumm/tabs/sei.py
  gwsumm/tests/test_config.py
  gwsumm/tests/test_plot.py
  requirements.txt
  setup.py
Labels: python3

#249 Use codecov for coverage
  .codecov.yml
  .travis.yml
  README.md
Labels: build-and-test

#250 More updates to gracedb event tabs
  gwsumm/tabs/gracedb.py
Labels: backwards-compatible

#253 Python 3 compatibility fixes
  bin/gw_summary
  gwsumm/tabs/core.py
Labels: bug-fix, python3

#254 Make __metaclass__ setting for the Tab Python 3 compatible
  gwsumm/tabs/core.py
Labels: backwards-compatible, bug-fix, python3

#257 Introducing public documentation for GWSumm
  .gitignore
  .readthedocs.yml
  README.rst
  docs/_static/css/custom.css
  docs/api/index.rst
  docs/automation.rst
  docs/cli.rst
  docs/conf.py
  docs/index.rst
  docs/install.rst
  docs/overview.rst
  docs/requirements.txt
Labels: enhancement

#258 Fixed use of Plot.add_legend
  gwsumm/plot/triggers.py
Labels: bug-fix, gwpy, plotter

#256 Unit tests for HTML construction
  gwsumm/html/bootstrap.py
  gwsumm/html/html5.py
  gwsumm/html/tests/__init__.py
  gwsumm/html/tests/test_bootstrap.py
  gwsumm/html/tests/test_html5.py
  gwsumm/html/tests/test_static.py
  setup.cfg
Labels: build-and-test, enhancement, html

#260 Fixed a few issues discovered in testing on python3
  gwsumm/archive.py
  gwsumm/tabs/etg.py
  gwsumm/tabs/sei.py
Labels: backwards-compatible, bug-fix, python3
