Repository gwpy/gwsumm, pull requests merged in 2023-11, with the labels that each got.

#384 Update readthedocs configuration
  .readthedocs.yaml
  docs/conf.py
Labels: build-and-test

#382 Fix case when data is missing at beginning of vt span
  gwsumm/plot/range.py
Labels: bug-fix

#354 Migrate to pyproject.toml
  .codeclimate.yml
  .flake8
  .github/workflows/build.yml
  .github/workflows/lint.yml
  .gitignore
  .gitmodules
  .readthedocs.yaml
  MANIFEST.in
  docs/conf.py
  docs/environment.yml
  gwsumm/__init__.py
  gwsumm/_version.py
  gwsumm/config/__init__.py
  gwsumm/config/defaults.ini
  gwsumm/config/matplotlib.ini
  gwsumm/tabs/core.py
  gwsumm/tests/test_config.py
  pyproject.toml
  setup.cfg
  setup.py
  versioneer.py
Labels: build-and-test, python3

#383 Update Axes.grid keyword to use 'visible'
  gwsumm/plot/builtin.py
  gwsumm/plot/core.py
  gwsumm/plot/noisebudget.py
  gwsumm/plot/segments.py
  gwsumm/plot/triggers/core.py
  pyproject.toml
Labels: plotter
